baseURL = "http://mode19.net/"
languageCode = "en-us"
title = "Mode 13h"
theme = "base16"
disqusShortName = "mode13h"

# Source code settings
# PygmentsCodeFences = true
# PygmentsStyle = "monokai"
# PygmentsOptions = "linenos=table"

[markup]
  [markup.highlight]
    codeFences = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'monokai'
    tabWidth = 4
